spring.application.name=vaultify-backend

spring.datasource.url=jdbc:mysql://localhost:3306/vaultify
spring.datasource.username=root
spring.datasource.password=492005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true